version: '3'

volumes:
  postgres_volume:

services:
  chat_db:
    image: postgres:14-alpine3.19
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "5775:5775/udp" # accept zipkin.thrift over compact thrift protocol
      - "6831:6831/udp" # jaeger-client accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # accept jaeger.thrift over binary thrift protocol
      - "5778:5778" # serve configs
      - "16686:16686" # web
      - "14268:14268" # accept jaeger.thrift directly from clients
      - "9411:9411" # zipkin Optional
